### ISSUE TITLE
FullAjaxExceptionHandler fails to include stylesheets in the error page

### ISSUE THREAD

**Issue by paulthomson78** [omnifaces/omnifaces#627]
**Issue**
When FullAjaxExceptionHandler renders an error page it is failing to include stylesheets included in that error page with h:outputStylesheet.

**Environment**
Omnifaces 2.7.11.
Java 8
WildFly 19.1.0, which is using jsf-impl-2.3.9.SP08.jar.

**Self diagnosis**
This was raised in https://stackoverflow.com/questions/53400252/houtputstylesheet-not-inserted-when-using-fullajaxexceptionhandler but no solution found.  So I've dug into the potential cause.

This JSF implementation's ScriptStyleBaseRenderer avoids duplicating stylesheets if they're already included:
```java
        // Ensure this resource is not rendered more than once per request.
        ResourceHandler resourceHandler = context.getApplication().getResourceHandler();
        if (resourceHandler.isResourceRendered(context, name, library)) {
            return;
        }
```
I've confirmed that when generating the error page it is seeing the stylesheet as already rendered and so is skipping it.  It is storing a `Set<String>` containing the resources in the context attributes under key `"/javax.faces.resource"`, which is the value of constant `ResourceHandler.RESOURCE_IDENTIFIER`.

There appears to be an attempt in FullAjaxExceptionHandler to clear out any pre-existing resources, using `Hacks.removeResourceDependencyState(context);`.  If that's indeed what that's supposed to be doing then it's not working with this JSF implementation.

**Workaround for testing**
Extend FullAjaxExceptionHandler and remove the resources via the addition of `context.getAttributes().remove(ResourceHandler.RESOURCE_IDENTIFIER);`.  This isn't a practical workaround though because it involved copy / pasting most of the FullAjaxExceptionHandler logic into the subclass, there wasn't anything easy to just override.

**Potential fix**
Add the constant `ResourceHandler.RESOURCE_IDENTIFIER`, i.e. `"/javax.faces.resource"`, to the set of keys that `Hacks.removeResourceDependencyState` removes from the context attributes.

**Comment by BalusC** [comment]
Fixed, thank you very much for reporting! This has indeed slipped through since JSF 2.3 changes.

**Comment by BalusC** [comment]
By the way, any technical reason why you aren't using OmniFaces 3.x instead of 2.x? OmniFaces 3.x is intended for JSF 2.3.

**Comment by paulthomson78** [comment]
Many thanks!

Re. the version, no there's no good reason we're using 2.x sorry.  I've tested that 3.11 works fine (other than still having the issue discussed here) and we'll upgrade to that.  Thanks for pointing that out.

**Comment by BalusC** [comment]
Reopening. While adding an integration test on this I discovered inconsistenties across JSF versions depending on the exact use case (the recently implemented solution did work as intented when exception occurred during render response, but it did not work as intended when exception occurred during invoke application in JSF 2.3). So I'll have to polish it a bit more.

**Comment by BalusC** [comment]
Fixed and covered by IT now.
