### ISSUE TITLE
o:tagAttribute with ID attribute and no attribute used

### ISSUE THREAD

**Issue by martin654** [omnifaces/omnifaces#754]
Hi, 
we are using OF version 3.14.2 and we experience issue with o:tagAttribute

Our tag is defined like this:
```
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:o="http://omnifaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

  <o:tagAttribute name="id"/>
  <o:tagAttribute name="align"/>
  <o:tagAttribute name="rendered" default="#{true}"/>

  <h:panelGroup id="#{id}" styleClass="buttons-container" layout="block" rendered="#{rendered}">
      <ui:insert/>
  </h:panelGroup>

</ui:composition>
```

and we sometimes use it like this without any attribute defined:
```
<tags:actions />
<tags:actions />
<tags:actions />
```

in this case duplicate IDs occur.

Everything works fine when any attribute defined:
```
<tags:actions align="left" />
<tags:actions align="right" />
<tags:actions align="left" />
```

Could you please check it? 

Thank you.

Best regards,
Martin

**Comment by BalusC** [comment]
Norepro with Mojarra 2.3.18 nor MyFaces 2.3.10.

Not sure what the possible cause of your problem is. Dirty build/classpath perhaps? Or something odd in taglib config?

**Comment by martin654** [comment]
Thank you for checking this. 

Our taglib config looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<facelet-taglib version="2.3" xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-facelettaglibrary_2_3.xsd">
  <namespace>http://xmlns.jcp.org/jsf/composite/test</namespace>

  <tag>
    <description>Actions is a wrapper for action commandButtons.</description>
    <tag-name>actions</tag-name>
    <source>resources/test/actions.xhtml</source>
    <attribute>
      <description>
        Optional. Set 'right' for right align. Default is left.
      </description>
      <name>align</name>
      <required>false</required>
      <type>java.lang.String</type>
    </attribute>
    <attribute>
      <description>
        Optional. ID is generated automatically when not defined.
      </description>
      <name>id</name>
      <required>false</required>
      <type>java.lang.String</type>
    </attribute>
    <attribute>
      <description>
        Optional. Set 'false' to disable rendering.
      </description>
      <name>rendered</name>
      <required>false</required>
      <type>java.lang.Boolean</type>
    </attribute>
  </tag>

</facelet-taglib>

```
and we use mojarra 2.3.19.

I will have to create reproducer outside our production project.

**Comment by martin654** [comment]
Hi, 
I finally found some time to create reproducer.

I used joinfaces example to do so. There is a clone of 4.7.x branch of joinfaces-example:

https://github.com/martin654/joinfaces-of-duplicate-id-reproduces/tree/of-id-reproducer

Changeset:
https://github.com/martin654/joinfaces-of-duplicate-id-reproduces/compare/4.7.x...of-id-reproducer

You should be able to build and run it using this documentation: https://github.com/joinfaces/joinfaces-maven-jar-example

Could you check it again please?

Thank you.

Best regards,
Martin

**Comment by BalusC** [comment]
Reproduced. It's only triggered when being placed in an UIForm.

**Comment by BalusC** [comment]
Fixed. Thank you very much for reporting and improving OmniFaces!

**Comment by martin654** [comment]
Thank you for the fix. Do you have plans for 3.x release anytime soon?

**Comment by martin654** [comment]
Hi again,
OF version 3.14.3 doesn't fix this issue completely.

Please see example below: (actionsSecon.xhtml is a simple copy and rename of the actions.xhtml tag)

```
<?xml version="1.0" encoding="UTF-8"?>
<facelet-taglib version="2.3" xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-facelettaglibrary_2_3.xsd">
  <namespace>http://xmlns.jcp.org/jsf/composite/test</namespace>

  <tag>
    <description>Actions is a wrapper for action commandButtons.</description>
    <tag-name>actions</tag-name>
    <source>actions.xhtml</source>
    <attribute>
      <description>
        Optional. Set 'right' for right align. Default is left.
      </description>
      <name>align</name>
      <required>false</required>
      <type>java.lang.String</type>
    </attribute>
    <attribute>
      <description>
        Optional. ID is generated automatically when not defined.
      </description>
      <name>id</name>
      <required>false</required>
      <type>java.lang.String</type>
    </attribute>
    <attribute>
      <description>
        Optional. Set 'false' to disable rendering.
      </description>
      <name>rendered</name>
      <required>false</required>
      <type>java.lang.Boolean</type>
    </attribute>
  </tag>

  <tag>
    <description>Actions is a wrapper for action commandButtons.</description>
    <tag-name>actionsSecond</tag-name>
    <source>actionsSecond.xhtml</source>
    <attribute>
      <description>
        Optional. Set 'right' for right align. Default is left.
      </description>
      <name>align</name>
      <required>false</required>
      <type>java.lang.String</type>
    </attribute>
    <attribute>
      <description>
        Optional. ID is generated automatically when not defined.
      </description>
      <name>id</name>
      <required>false</required>
      <type>java.lang.String</type>
    </attribute>
    <attribute>
      <description>
        Optional. Set 'false' to disable rendering.
      </description>
      <name>rendered</name>
      <required>false</required>
      <type>java.lang.Boolean</type>
    </attribute>
  </tag>

</facelet-taglib>

```

actions.xhtml:
```
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:o="http://omnifaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

  <o:tagAttribute name="id"/>
  <o:tagAttribute name="align"/>
  <o:tagAttribute name="rendered" default="#{true}"/>

  <h:panelGroup id="#{id}" styleClass="fob-action" layout="block" rendered="#{rendered}">
    <p:divider/>
    <div class="fob-button-container #{align eq 'right' ? 'justify-content-end':''}">
      ACTIONS FIRST
      <ui:insert/>
    </div>
  </h:panelGroup>

</ui:composition>
```

actionsSecond.xhtml:
```
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:o="http://omnifaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

  <o:tagAttribute name="id"/>
  <o:tagAttribute name="align"/>
  <o:tagAttribute name="rendered" default="#{true}"/>

  <h:panelGroup id="#{id}" styleClass="fob-action" layout="block" rendered="#{rendered}">
    <p:divider/>
    <div class="fob-button-container #{align eq 'right' ? 'justify-content-end':''}">
      ACTIONS SECOND
      <ui:insert/>
    </div>
  </h:panelGroup>

</ui:composition>
```

**This fails:**
```
<h:form>
  <test:actions />
  <test:actionsSecond align="left"/>
</h:form>
```

java.lang.IllegalStateException: Component ID j_idt9:j_ido2110982517_334fa3be has already been found in the view.

**If you ommit all attributes, it works:**
```
<h:form>
  <test:actions />
  <test:actionsSecond/>
</h:form>
```

**It also works if both tags have some attribute:**
```
<h:form>
  <test:actions align="left"/>
  <test:actions align="right"/>
</h:form>
```

**This also works:**
```
<h:form>
  <test:actions align="left"/>
  <test:actions align="right"/>

  <test:actionsSecond />
  <test:actionsSecond />
</h:form>
```

**And this fails too:**
```
<h:form>
  <test:actions />
  <test:actions align="right"/>
</h:form>

```
It looks like the order of tags is important. If you use no arg tag first, it fails.

@BalusC  could you check it, please?

Thanks

**Comment by BalusC** [comment]
Hopefully fixed for good now, thank you!
